"""Difficulty analysis of LilyPond harmonica scores.

Counts the notes needing a special technique (bends, overblows, overdraws),
the big jumps between the holes of two successive notes, the notes played in
the high register (holes 9-10), and estimates the speed from the tempo and the
shortest note value. The resulting formula is documented on the
difficulte.html page generated by generate_index.py.
"""

import re
from html import escape

# --------- Constants ---------

FRENCH_NOTES  = {'sol': 7, 'do': 0, 're': 2, 'mi': 4, 'fa': 5, 'la': 9, 'si': 11}
ENGLISH_NOTES = {'c': 0, 'd': 2, 'e': 4, 'f': 5, 'g': 7, 'a': 9, 'b': 11}

TUNING_ROOTS: dict[str, int] = {
    'diatonicHarmonicaTab':       0,
    'diatonicDHarmonicaTab':      2,
    'diatonicEHarmonicaTab':      4,
    'diatonicGHarmonicaTab':      7,
    'diatonicAHarmonicaTab':      9,
    'diatonicFHarmonicaTab':      5,
    'diatonicBbHarmonicaTab':     10,
    'diatonicSuzukiFiveHarmonicaTab': 0,
}

# Semitone offset (from harmonica root) -> (hole, technique), mirroring
# get-diatonic-ritcher-tab and get-diatonic-suzuki-5-c-tab in include/harmonica.ly.
# 'natural' covers plain blow and draw notes.
RICHTER_LAYOUT: dict[int, tuple[int, str]] = {
    0:  (1, 'natural'),  1:  (1, 'bend'),     2:  (1, 'natural'),  3:  (1, 'overblow'),
    4:  (2, 'natural'),  5:  (2, 'bend'),     6:  (2, 'bend'),     7:  (2, 'natural'),
    8:  (3, 'bend'),     9:  (3, 'bend'),     10: (3, 'bend'),     11: (3, 'natural'),
    12: (4, 'natural'),  13: (4, 'bend'),     14: (4, 'natural'),  15: (4, 'overblow'),
    16: (5, 'natural'),  17: (5, 'natural'),  18: (5, 'overblow'),
    19: (6, 'natural'),  20: (6, 'bend'),     21: (6, 'natural'),  22: (6, 'overblow'),
    23: (7, 'natural'),  24: (7, 'natural'),  25: (7, 'overdraw'),
    26: (8, 'natural'),  27: (8, 'bend'),     28: (8, 'natural'),
    29: (9, 'natural'),  30: (9, 'bend'),     31: (9, 'natural'),  32: (9, 'overdraw'),
    33: (10, 'natural'), 34: (10, 'bend'),    35: (10, 'bend'),    36: (10, 'natural'),
}

SUZUKI_FIVE_LAYOUT: dict[int, tuple[int, str]] = {
    0:  (1, 'natural'), 2:  (1, 'natural'),
    4:  (2, 'natural'), 5:  (2, 'natural'),
    7:  (3, 'natural'), 9:  (3, 'natural'),
    11: (4, 'natural'), 12: (4, 'natural'),
    14: (5, 'natural'), 16: (5, 'natural'),
}

# Weights of each difficulty factor in the technique score
WEIGHT_BEND     = 1
WEIGHT_OVERBLOW = 3
WEIGHT_OVERDRAW = 3
WEIGHT_JUMP     = 1    # per hole beyond JUMP_MIN_HOLES - 1
WEIGHT_HIGH     = 0.5  # per note on a hole >= HIGH_HOLE_MIN

JUMP_MIN_HOLES = 3  # a jump of at least this many holes is a "grand écart"
HIGH_HOLE_MIN  = 9

# Technique score thresholds: 0 -> facile, <= LEVEL_MEDIUM_MAX -> moyen, else difficile
LEVEL_MEDIUM_MAX = 5

# Defaults when the score has no \tempo or no explicit duration
DEFAULT_TEMPO   = 100
DEFAULT_FASTEST = 4

# Speed index = tempo x fastest / SPEED_DIVISOR (1 = one quarter note at 60 bpm)
SPEED_DIVISOR = 240
SPEED_LEVELS = [  # (minimum speed index, badge, label), fastest first
    (7, '⚡', 'très rapide'),
    (4, '🏃', 'rapide'),
    (2, '🎵', 'modéré'),
    (0, '🐢', 'lent'),
]


# --------- LilyPond helpers ---------

def strip_comments(text: str) -> str:
    text = re.sub(r'%\{.*?%\}', '', text, flags=re.DOTALL)
    return re.sub(r'%[^\n]*', '', text)


def brace_block(text: str, start: int) -> str:
    depth, i = 1, start
    while i < len(text) and depth:
        c = text[i]
        if c == '{':   depth += 1
        elif c == '}': depth -= 1
        i += 1
    return text[start:i - 1]


def inline_music_variables(content: str, melody: str) -> str:
    """Expand `\\name` references to `name = { ... }` blocks defined in the file.

    Lets a song split `melodie` into parts (e.g. for a D.S. al Coda MIDI path)
    while the notes are still analysed once, in written order.
    """
    defs = {m.group(1): brace_block(content, m.end())
            for m in re.finditer(r'\b([A-Za-z]+)\s*=\s*\{', content)
            if m.group(1) != 'melodie'}
    for _ in range(5):
        expanded = re.sub(r'\\([A-Za-z]+)\b',
                          lambda m: defs.get(m.group(1), m.group(0)), melody)
        if expanded == melody:
            break
        melody = expanded
    return melody


# --------- Difficulty analysis ---------

def analyze_difficulty(content: str) -> dict:
    content = strip_comments(content)
    is_french = bool(re.search(r'language\s*"fran', content))
    notes_map = FRENCH_NOTES if is_french else ENGLISH_NOTES

    root = 0
    for fn, r in TUNING_ROOTS.items():
        if re.search(rf'\\{fn}\b', content):
            root = r
            break
    is_suzuki = bool(re.search(r'\\diatonicSuzukiFiveHarmonicaTab\b', content))
    layout = SUZUKI_FIVE_LAYOUT if is_suzuki else RICHTER_LAYOUT

    tempo = None
    m = re.search(r'\\tempo\s+\d+\.?\s*=\s*(\d+)', content)
    if m:
        tempo = int(m.group(1))

    m_mel = re.search(r'\bmelodie\s*=\s*\{', content)
    melody = brace_block(content, m_mel.end()) if m_mel else content
    melody = inline_music_variables(content, melody)

    current = 60
    names_sorted = sorted(notes_map.keys(), key=len, reverse=True)
    names_alt = '|'.join(names_sorted)
    m_rel = re.search(rf'\\relative\s+({names_alt})([\',]*)', content)
    if m_rel:
        start_class = notes_map[m_rel.group(1)]
        mods = m_rel.group(2)
        current = 48 + start_class + mods.count("'") * 12 - mods.count(",") * 12

    # Strip \key <tonic> \major/\minor first: otherwise the generic backslash-
    # command stripping below removes only "\key", leaving the tonic name
    # (e.g. "sol" from "\key sol \major") behind as a phantom extra note.
    melody = re.sub(r'\\key\s+\S+\s+\\(major|minor)', ' ', melody)
    melody = re.sub(r'\\[a-zA-Z]+(?:\s*\{[^{}]*\})?', ' ', melody)
    melody = re.sub(r'"[^"]*"', ' ', melody)
    melody = re.sub(r'#[^|\n{} ]*', ' ', melody)

    if is_french:
        note_re = re.compile(
            rf'(?<![a-zA-Z])({names_alt})(dd|d|bb|b)?([\',]*)(\d+)?(\.+)?(?![a-zA-Z])'
        )
    else:
        note_re = re.compile(
            r"(?<![a-zA-Z])([cdefgab])(isis|eses|is|es)?([\',]*)(\d+)?(\.+)?(?![a-zA-Z])"
        )

    counts = {'bend': 0, 'overblow': 0, 'overdraw': 0}
    jumps = jump_holes = high_notes = 0
    prev_hole = None
    fastest = None

    for m in note_re.finditer(melody):
        name    = m.group(1)
        acc     = m.group(2) or ''
        oct_str = m.group(3) or ''
        dur_str = m.group(4)

        base = notes_map.get(name, 0)
        if is_french:
            base += acc.count('d') - acc.count('b')
        else:
            if 'isis' in acc:   base += 2
            elif 'is' in acc:   base += 1
            elif 'eses' in acc: base -= 2
            elif 'es' in acc:   base -= 1
        base %= 12

        diff_up = (base - current % 12) % 12
        abs_p   = (current + diff_up) if diff_up <= 6 else (current - (12 - diff_up))
        abs_p  += oct_str.count("'") * 12 - oct_str.count(",") * 12
        current = abs_p

        if dur_str:
            d = int(dur_str)
            if fastest is None or d > fastest:
                fastest = d

        # Notes outside the harmonica range (tab "X") are skipped.
        entry = layout.get(abs_p - 60 - root)
        if entry is None:
            continue
        hole, technique = entry
        if technique in counts:
            counts[technique] += 1
        if hole >= HIGH_HOLE_MIN:
            high_notes += 1
        if prev_hole is not None:
            gap = abs(hole - prev_hole)
            if gap >= JUMP_MIN_HOLES:
                jumps += 1
                jump_holes += gap - (JUMP_MIN_HOLES - 1)
        prev_hole = hole

    return {
        'bends': counts['bend'], 'overblows': counts['overblow'],
        'overdraws': counts['overdraw'],
        'jumps': jumps, 'jump_holes': jump_holes, 'high_notes': high_notes,
        'tempo': tempo, 'fastest_note': fastest,
    }


def technique_score(diff: dict) -> float:
    return (
        WEIGHT_BEND     * diff.get('bends', 0)
        + WEIGHT_OVERBLOW * diff.get('overblows', 0)
        + WEIGHT_OVERDRAW * diff.get('overdraws', 0)
        + WEIGHT_JUMP     * diff.get('jump_holes', 0)
        + WEIGHT_HIGH     * diff.get('high_notes', 0)
    )


def speed_index(diff: dict) -> float:
    tempo   = diff.get('tempo') or DEFAULT_TEMPO
    fastest = diff.get('fastest_note') or DEFAULT_FASTEST
    return tempo * fastest / SPEED_DIVISOR


def difficulty_sort_value(diff: dict) -> float:
    return technique_score(diff) + speed_index(diff)


def difficulty_cell(diff: dict) -> str:
    bends      = diff.get('bends', 0)
    overblows  = diff.get('overblows', 0)
    overdraws  = diff.get('overdraws', 0)
    jumps      = diff.get('jumps', 0)
    high_notes = diff.get('high_notes', 0)
    tempo      = diff.get('tempo') or DEFAULT_TEMPO
    fastest    = diff.get('fastest_note') or DEFAULT_FASTEST

    speed = speed_index(diff)
    speed_badge, speed_label = next(
        (badge, label) for threshold, badge, label in SPEED_LEVELS if speed >= threshold
    )

    weight = technique_score(diff)
    if weight == 0:
        level, level_label = '🟢', 'facile'
    elif weight <= LEVEL_MEDIUM_MAX:
        level, level_label = '🟡', 'moyen'
    else:
        level, level_label = '🔴', 'difficile'

    parts   = [level]
    details = [level_label]
    if bends:
        parts.append(f'↕{bends}')
        details.append(f"{bends} altération(s) / bend(s)")
    if overblows:
        parts.append(f'⊕{overblows}')
        details.append(f"{overblows} overblow(s)")
    if overdraws:
        parts.append(f'⊗{overdraws}')
        details.append(f"{overdraws} overdraw(s)")
    if jumps:
        parts.append(f'↔{jumps}')
        details.append(f"{jumps} grand(s) écart(s) de trous")
    if high_notes:
        parts.append(f'▲{high_notes}')
        details.append(f"{high_notes} note(s) aiguë(s) (trous {HIGH_HOLE_MIN}-10)")
    parts.append(speed_badge)
    details.append(f'{speed_label} (♩={tempo}, 1/{fastest})')

    sort_val = difficulty_sort_value(diff)
    tooltip  = escape(' | '.join(details))
    content  = ' '.join(parts)
    return f"<td data-sort='{sort_val:.2f}' title='{tooltip}' style='white-space:nowrap'>{content}</td>"
